apiVersion: core.oxia.io/v1
kind: TCBasicKV
metadata:
  labels:
    app.kubernetes.io/name: manager
    app.kubernetes.io/managed-by: kustomize
  name: tcbasickv-sample
spec:
  # TODO(user): Add fields here
