apiVersion: core.oxia.io/v1
kind: TCMetadataEphemeral
metadata:
  labels:
    app.kubernetes.io/name: manager
    app.kubernetes.io/managed-by: kustomize
  name: tcmetadataephemeral-sample
spec:
  # TODO(user): Add fields here
