apiVersion: v2
name: okk-stack
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: okk-manager
    version: "0.1.0"
    repository: file://../okk-manager
  - name: kube-prometheus-stack
    version: "58.2.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: chaos-mesh
    version: "2.7.2"
    repository: "https://charts.chaos-mesh.org"