global:
  namespace: okk-system

okk-manager:
  image: "mattison/okk-manager"
  replicas: 0

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: { }
  grafana:
    adminPassword: "admin"

chaos-mesh:
  namespace: "{{ .Values.global.namespace }}"
  dashboard:
    securityMode: false