---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.oxia.io
  resources:
  - oxiaclusters
  - tcbasickvs
  - tcbasicsecondaryindices
  - tcmetadataephemerals
  - tcmetadatanotifications
  - tcstreamingsequences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oxia.io
  resources:
  - oxiaclusters/finalizers
  - tcbasickvs/finalizers
  - tcbasicsecondaryindices/finalizers
  - tcmetadataephemerals/finalizers
  - tcmetadatanotifications/finalizers
  - tcstreamingsequences/finalizers
  verbs:
  - update
- apiGroups:
  - core.oxia.io
  resources:
  - oxiaclusters/status
  - tcbasickvs/status
  - tcbasicsecondaryindices/status
  - tcmetadataephemerals/status
  - tcmetadatanotifications/status
  - tcstreamingsequences/status
  verbs:
  - get
  - patch
  - update
