# This rule is not used by the project manager itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.oxia.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: manager
    app.kubernetes.io/managed-by: kustomize
  name: tcstreamingsequence-admin-role
rules:
- apiGroups:
  - core.oxia.io
  resources:
  - tcstreamingsequences
  verbs:
  - '*'
- apiGroups:
  - core.oxia.io
  resources:
  - tcstreamingsequences/status
  verbs:
  - get
